### ISSUE TITLE
Atualização de informações necessárias para o pleno funcionamento do mock

### ISSUE THREAD

**Issue by beatrizodsk** [Intmed-Software/desafio-mock-server#1]
Ao tentar utilizar o mock me deparei com um erro específico com relação ao cors. 
![image](https://user-images.githubusercontent.com/65625601/158687185-b78d8bbe-1298-4a8a-93a1-b6c0ecdd5ac4.png)

Para conseguir utilizar a api segui os seguintes passos: 
1 - instalar a biblioteca cors com o comando 'yarn add cors' no cmd
2 - importar cors no index.js do mock com a seguinte linha de código: import cors from "cors";
3 - adicionar a linha : app.use(cors()); 
entre: const app = express();
e: app.use(express.json());

**Comment by brunobarretofreitas** [comment]
Muito obrigado pelo report Beatriz, iremos atualizar a aplicação.
Qualquer dúvida ou sugestão sobre o desafio estamos a disposição :)
