### ISSUE TITLE
Problema com filtro na api

### ISSUE THREAD

**Issue by beatrizodsk** [Intmed-Software/desafio-mock-server#2]
Ao tentar realizar o filtro da agenda de um médico o mesmo está retornando mais de um médico.

![image](https://user-images.githubusercontent.com/65625601/159006672-66ffd7e0-fc29-46c1-80c4-7c9715cb387d.png)
![image](https://user-images.githubusercontent.com/65625601/159006815-f53c579c-0335-4798-9623-3193005d3096.png)

Gostaria de saber como proceder.

**Comment by brunobarretofreitas** [comment]
Olá @BeatrizOSantos, como é apenas um mock, está sempre retornando os mesmos valores, então não há problema dos dados não virem filtrados. Iremos avaliar em seu desafio apenas como você resolveu em código a filtragem :)

**Comment by beatrizodsk** [comment]
Certo, muito obrigada!
